# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-05 13:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('afisha', '0003_auto_20161204_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 5, 13, 43, 55, 681706, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
